Updating sonar github action to also retrieve and upload hotspots
pixee/upload-tool-results-action pull request #11
Opened 2024-05-07 17:46 UTC by carlosu7

Related issue: https://github.com/pixee/upload-tool-results-action/issues/7

![Screenshot 2024-05-07 at 11 45 09 a m](https://github.com/pixee/upload-tool-results-action/assets/14047435/d6b5d103-9967-4c32-a39f-3ab20c8cb8d2)

2024-05-07 17:46 UTC, carlosu7 commented on dist/index.js
this file was uploaded just for testing purposes but it won't be merged

2024-05-07 18:10 UTC, carlosu7 commented on src/sonar.ts
> +  )}&resolved=false&ps=${MAX_PAGE_SIZE}`;
Updating page size limit to 500 

Issue: https://github.com/pixee/upload-tool-results-action/issues/10

2024-05-08 19:07 UTC, drdavella requested changes
Looks good overall but we need to make sure we're using the correct analysis inputs parameters to distinguish between issues and hotspots.

2024-05-08 19:07 UTC, drdavella commented on src/sonar.ts
> +export async function retrieveSonarCloudHotspots(
I understand why this is a separate function but it seems to share a lot of code with `retrieveSonarCloudIssues` 🤔

2024-05-09 18:47 UTC, carlosu7 commented on src/sonar.ts
> +const MAX_PAGE_SIZE = 500;
@drdavella should i add that change now?

2024-05-09 18:56 UTC, carlosu7 commented on src/action.ts
> +      await uploadInputFile(tool, issuesfile);
the purpose of that change is because of the way the URL is built and used to upload the files to pixee, right? @drdavella

2024-05-09 20:13 UTC, drdavella commented on src/action.ts
> +      await uploadInputFile(tool, issuesfile);
Yes that's right, Pixeebot stores sonar issues and sonar hotspots in separate buckets so we need to upload them to different endpoints.

2024-05-09 20:21 UTC, drdavella commented on src/sonar.ts
> +const MAX_PAGE_SIZE = 500;
I don't think it's necessary but you can if you want to.

2024-05-10 15:31 UTC, drdavella approved these changes

2024-05-10 17:41 UTC, merged