Add support for Contrast results
pixee/upload-tool-results-action pull request #19
Opened 2024-05-24 06:37 UTC by JesusCotlamee

Support for downloading Contrast results has been added. These results will be uploaded to Pixee. You can review the request at the following link https://github.com/pixee/upload-tool-results-action/issues/16.

Evidence:
Check action https://github.com/JesusCotlamee/pixeebot-test-pull-request-response/actions/runs/9219736706

2024-05-24 19:01 UTC, fjpgtt requested changes

2024-05-27 19:29 UTC, fjpgtt requested changes

2024-05-27 19:29 UTC, fjpgtt commented on src/action.ts
> +async function fetchOrLocateContrastResultsFile(tool: Tool) {
I think you no longer need to pass the Tool, you can pass an String to the fetchOrLocateResultsFile

2024-05-27 19:29 UTC, fjpgtt commented on src/action.ts
> +async function fetchOrLocateResultsFile(tool: string, results: any, fileName: string, stringifyResults: boolean = true) {
Can you update the default case (Line 45), so only calls the core.getInput, since it will never do the logic about the writign the file

2024-05-27 20:52 UTC, fjpgtt approved these changes

2024-05-29 02:05 UTC, drdavella requested changes
Looks very good overall. The main substantive comment is that the new Contrast fields cannot be marked as `required` in the `action.yml` file.

2024-05-29 02:05 UTC, drdavella commented on src/action.ts
> +async function fetchOrLocateResultsFile(tool: string, results: any, fileName: string, stringifyResults: boolean = true) {
Why can't this be `Tool`?

2024-05-29 18:44 UTC, JesusCotlamee commented on action.yml
> +    required: true
Thanks

2024-05-29 18:45 UTC, JesusCotlamee commented on src/action.ts
> +async function fetchOrLocateResultsFile(tool: string, results: any, fileName: string, stringifyResults: boolean = true) {
My mistake.

2024-05-30 15:08 UTC, drdavella approved these changes

2024-05-30 18:24 UTC, merged